#include "wrapper.hpp"

extern "C" {
    WRAP_FUNC_VOID(glTranslated)
    WRAP_FUNC_VOID(glNormal3f)
    WRAP_FUNC_VOID(glBegin)
    WRAP_FUNC_VOID(glEnd)
    WRAP_FUNC_VOID(glEnable)
    WRAP_FUNC_VOID(glMatrixMode)
    WRAP_FUNC_VOID(glClear)
    WRAP_FUNC(glGenLists)
    WRAP_FUNC_VOID(glLoadIdentity)
    WRAP_FUNC_VOID(glShadeModel)
    WRAP_FUNC_VOID(glDrawBuffer)
    WRAP_FUNC_VOID(glFrustum)
    WRAP_FUNC_VOID(glTranslatef)
    WRAP_FUNC_VOID(glNewList)
    WRAP_FUNC_VOID(glEndList)
    WRAP_FUNC_VOID(glMaterialfv)
    WRAP_FUNC_VOID(glRotatef)
    WRAP_FUNC_VOID(glLightfv)
    WRAP_FUNC_VOID(glVertex3f)
    WRAP_FUNC_VOID(glPushMatrix)
    WRAP_FUNC(glGetString)
    WRAP_FUNC_VOID(glCallList)
    WRAP_FUNC_VOID(glPopMatrix)
    WRAP_FUNC_VOID(glViewport)
    WRAP_FUNC_VOID(glDeleteLists)

    WRAP_FUNC(glXMakeCurrent)
    WRAP_FUNC_VOID(glXGetProcAddressARB)
    WRAP_FUNC_VOID(glXDestroyContext)
    WRAP_FUNC(glXCreateContext)
    WRAP_FUNC_VOID(glXQueryDrawable)
    WRAP_FUNC_VOID(glXSwapBuffers)
    WRAP_FUNC(glXChooseVisual)
    WRAP_FUNC(glXQueryExtensionsString)
}