#include "wrapper.h"

WRAP_FUNC(sin)
WRAP_FUNC(sinf)
WRAP_FUNC(asinf)
WRAP_FUNC(cos)
WRAP_FUNC(cosf)
WRAP_FUNC(acosf)
WRAP_FUNC(tan)
WRAP_FUNC(tanf)
WRAP_FUNC(atanf)
WRAP_FUNC(atan2f)
WRAP_FUNC(sqrt)
WRAP_FUNC(pow)
WRAP_FUNC(round)
WRAP_FUNC(ceil)
WRAP_FUNC(fmod)
WRAP_FUNC(fmodf)
WRAP_FUNC(modff)
WRAP_FUNC(sqrtf)
WRAP_FUNC(expf)

WRAP_FUNC(log10)
WRAP_FUNC(dup)
WRAP_FUNC(dup2)